import type { User, Listing, DealRoom, DealRoomMessage } from './types';

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

export const mockUsers: User[] = [
  {
    id: 'user_seller_1',
    walletAddress: '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
    email: 'seller@example.com',
    kycStatus: 'VERIFIED',
    role: 'SELLER',
    accreditedInvestorAttestation: true,
    didTokenId: 'did:ink:0x742d35Cc',
    createdAt: new Date('2025-11-15'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'user_buyer_1',
    walletAddress: '0x8ba1f109551bD432803012645Ac136ddd64DBA72',
    email: 'buyer@example.com',
    kycStatus: 'VERIFIED',
    role: 'BUYER',
    pofTier: 'TIER_3',
    pofMethod: 'STABLECOIN_WALLET',
    pofVerifiedAt: new Date('2026-03-10'),
    accreditedInvestorAttestation: true,
    didTokenId: 'did:ink:0x8ba1f109',
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2026-03-10'),
  },
];

export const mockListings: Listing[] = [
  {
    id: 'listing_1',
    sellerId: 'user_seller_1',
    companyName: 'SpaceX',
    companyLogo: `${basePath}/logos/spacex.svg`,
    shareClass: 'Common',
    quantityMin: 100,
    quantityMax: 500,
    askPriceMin: 95,
    askPriceMax: 110,
    impliedValuation: 250_000_000_000,
    posMethod: 'DOCUMENT_HASH',
    posVerified: true,
    posAttestationHash: '0xabc123...',
    posVerifiedAt: new Date('2026-02-01'),
    certificateHash: '0xdef456...',
    transferAgentVerified: false,
    escrowVerified: false,
    rofrWaiver: true,
    lockupExpired: true,
    rule144Compliant: true,
    status: 'ACTIVE',
    expiresAt: new Date('2026-06-01'),
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'listing_2',
    sellerId: 'user_seller_1',
    companyName: 'Stripe',
    companyLogo: `${basePath}/logos/stripe.svg`,
    shareClass: 'Preferred',
    quantityMin: 50,
    quantityMax: 200,
    askPriceMin: 28,
    askPriceMax: 35,
    impliedValuation: 65_000_000_000,
    posMethod: 'TRANSFER_AGENT',
    posVerified: true,
    posAttestationHash: '0x789abc...',
    posVerifiedAt: new Date('2026-01-15'),
    transferAgentVerified: true,
    escrowVerified: false,
    rofrWaiver: true,
    lockupExpired: true,
    rule144Compliant: true,
    status: 'ACTIVE',
    expiresAt: new Date('2026-07-15'),
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'listing_3',
    sellerId: 'user_seller_1',
    companyName: 'Databricks',
    companyLogo: `${basePath}/logos/databricks.svg`,
    shareClass: 'Common',
    quantityMin: 200,
    quantityMax: 1000,
    askPriceMin: 42,
    askPriceMax: 50,
    impliedValuation: 43_000_000_000,
    posVerified: false,
    transferAgentVerified: false,
    escrowVerified: false,
    rofrWaiver: false,
    lockupExpired: true,
    rule144Compliant: true,
    status: 'ACTIVE',
    expiresAt: new Date('2026-05-01'),
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'listing_4',
    sellerId: 'user_seller_1',
    companyName: 'Canva',
    companyLogo: `${basePath}/logos/canva.svg`,
    shareClass: 'Common',
    quantityMin: 500,
    quantityMax: 2000,
    askPriceMin: 18,
    askPriceMax: 24,
    impliedValuation: 26_000_000_000,
    posMethod: 'ESCROW',
    posVerified: true,
    posAttestationHash: '0xescrow789...',
    posVerifiedAt: new Date('2026-02-20'),
    transferAgentVerified: false,
    escrowVerified: true,
    rofrWaiver: true,
    lockupExpired: true,
    rule144Compliant: true,
    status: 'ACTIVE',
    expiresAt: new Date('2026-08-20'),
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'listing_5',
    sellerId: 'user_seller_1',
    companyName: 'Anduril',
    companyLogo: `${basePath}/logos/anduril.svg`,
    shareClass: 'Preferred',
    quantityMin: 75,
    quantityMax: 300,
    askPriceMin: 55,
    askPriceMax: 68,
    impliedValuation: 14_000_000_000,
    posMethod: 'DOCUMENT_HASH',
    posVerified: true,
    posAttestationHash: '0xanduril...',
    posVerifiedAt: new Date('2026-03-05'),
    certificateHash: '0xandurilcert...',
    transferAgentVerified: false,
    escrowVerified: false,
    rofrWaiver: true,
    lockupExpired: true,
    rule144Compliant: true,
    status: 'ACTIVE',
    expiresAt: new Date('2026-09-05'),
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'listing_6',
    sellerId: 'user_seller_1',
    companyName: 'Discord',
    companyLogo: `${basePath}/logos/discord.svg`,
    shareClass: 'Options',
    quantityMin: 1000,
    quantityMax: 5000,
    askPriceMin: 8,
    askPriceMax: 12,
    impliedValuation: 15_000_000_000,
    posVerified: false,
    transferAgentVerified: false,
    escrowVerified: false,
    rofrWaiver: false,
    lockupExpired: false,
    rule144Compliant: false,
    status: 'ACTIVE',
    expiresAt: new Date('2026-04-15'),
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
];

export const mockDealRooms: DealRoom[] = [];
export const mockDealRoomMessages: DealRoomMessage[] = [];

// Mutable store for runtime
export const store = {
  users: [...mockUsers],
  listings: [...mockListings],
  dealRooms: mockDealRooms,
  messages: mockDealRoomMessages,
  currentUserId: null as string | null,
};
